# Plugin Shop
#
# https://discord.gg/pocketmine
# https://maxoooz.mysellix.io/

# All items you want to remove from the workbench
# You can set the meta "-1" or not set it all to include all items
delete: []

new:
  -
    shape:
      - "A A"
      - "A A"
    input:
      A: "netherite_ingot"
    output: "netherite_boots"
    remove-old-crafts: false
  -
    shape:
      - "AAA"
      - "A A"
    input:
      A: "netherite_ingot"
    output: "netherite_helmet"
    remove-old-crafts: false
  -
    shape:
      - "AAA"
      - "A A"
      - "A A"
    input:
      A: "netherite_ingot"
    output: "netherite_leggings"
    remove-old-crafts: false
  -
    shape:
      - "A A"
      - "AAA"
      - "AAA"
    input:
      A: "netherite_ingot"
    output: "netherite_chestplate"
    remove-old-crafts: false
  -
    shape:
      - " BB"
      - " A"
      - " A"
    input:
      A: "stick"
      B: "netherite_ingot"
    output: "netherite_hoe"
    remove-old-crafts: false
  -
    shape:
      - " B"
      - " A"
      - " A"
    input:
      A: "stick"
      B: "netherite_ingot"
    output: "netherite_shovel"
    remove-old-crafts: false
  -
    shape:
      - "BB"
      - "BA"
      - " A"
    input:
      A: "stick"
      B: "netherite_ingot"
    output: "netherite_axe"
    remove-old-crafts: false
  -
    shape:
      - "BBB"
      - " A"
      - " A"
    input:
      A: "stick"
      B: "netherite_ingot"
    output: "netherite_pickaxe"
    remove-old-crafts: false
  -
    shape:
      - "B"
      - "B"
      - "A"
    input:
      A: "stick"
      B: "netherite_ingot"
    output: "netherite_sword"
    remove-old-crafts: false
